import{S as b,a as S,i as c}from"./assets/vendor-DA7D1P1a.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const q=new b(".gallery a"),m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more");function g(a){const r=a.map(t=>`
        <li>
          <a href="${t.largeImageURL}">
            <img src="${t.webformatURL}" alt="${t.tags}" />
          </a>
          <p>Likes: ${t.likes}</p>
          <p>Views: ${t.views}</p>
          <p>Comments: ${t.comments}</p>
          <p>Downloads: ${t.downloads}</p>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",r),q.refresh()}function P(){m.innerHTML=""}function p(){h.classList.add("is-visible")}function L(){h.classList.remove("is-visible")}function w(){y.classList.add("hidden")}function i(){y.classList.remove("hidden")}function v(a,r,t){return S.get("https://pixabay.com/api/",{params:{q:a,page:r,per_page:t,key:"56332607-bb747eac8cf621789c682c14a",image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(s=>s.data)}const M=document.querySelector(".load-more");let f="",n=1;const l=15;let u=0;i();const x=document.querySelector(".form");x.addEventListener("submit",async a=>{a.preventDefault(),n=1,i();const r=document.querySelector('[name="search-text"]');if(i(),r.value.trim()!==""){f=r.value.trim(),P(),p();try{const t=await v(f,n,l),s=t.hits;if(u=t.totalHits,s.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(s);const e=Math.ceil(u/l);n<e?w():i()}catch(t){c.error({message:t.message||"Something went wrong. Please try again."})}finally{L(),r.value=""}}});M.addEventListener("click",async a=>{a.preventDefault(),n+=1,p();try{const r=await v(f,n,l);u=r.totalHits;const t=Math.ceil(u/l),s=r.hits;g(s);const e=document.querySelector(".gallery li");if(e){const o=e.getBoundingClientRect().height;window.scrollBy({top:o*3,behavior:"smooth"})}if(n>=t){i(),c.info({message:"We're sorry, but you've reached the end of search results."});return}else w()}catch(r){c.error({message:r.message||"Something went wrong. Please try again."})}finally{L()}});
//# sourceMappingURL=index.js.map
