import{S as b,a as S,i}from"./assets/vendor-DA7D1P1a.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const q=new b(".gallery a"),m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more");function g(n){const r=n.map(e=>`
        <li>
          <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" />
          </a>
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",r),q.refresh()}function M(){m.innerHTML=""}function p(){h.classList.add("is-visible")}function L(){h.classList.remove("is-visible")}function v(){y.classList.remove("hidden")}function a(){y.classList.add("hidden")}async function w(n,r,e=15){return e<15&&(e=15),(await S.get("https://pixabay.com/api/",{params:{q:n,page:r,per_page:e,key:"56332607-bb747eac8cf621789c682c14a",image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const P=document.querySelector(".load-more");let f="",c=1;const l=15;let u=0;a();const x=document.querySelector(".form");x.addEventListener("submit",async n=>{n.preventDefault(),c=1,a();const r=document.querySelector('[name="search-text"]');if(a(),r.value.trim()!==""){f=r.value.trim(),M(),a(),p();try{const e=await w(f,c,l),s=e.hits;if(u=e.totalHits,s.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"}),a();return}g(s);const t=Math.ceil(u/l);c<t?v():(a(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch(e){i.error({message:e.message||"Something went wrong. Please try again."})}finally{L(),r.value=""}}});P.addEventListener("click",async n=>{n.preventDefault(),c+=1,a(),p();try{const r=await w(f,c,l);u=r.totalHits;const e=Math.ceil(u/l),s=r.hits;if(!s||s.length===0){a(),i.info({message:"We're sorry, but you've reached the end of search results."});return}g(s);const t=document.querySelector(".gallery li");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}if(c>=e){a(),i.info({message:"We're sorry, but you've reached the end of search results."});return}else v()}catch(r){i.error({message:r.message||"Something went wrong. Please try again."})}finally{L()}});
//# sourceMappingURL=index.js.map
